spring:
  application:
    name: nacos-consumer
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: hello-consumer
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080

feign:
  sentinel:
    enabled: true

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"